---
ID: "35f3051a-dcbc-4183-93b4-18fdb883c769"
Parent: "3616546f-b468-4345-b5da-2a83be98fdd4"
Template: "fe96b853-6213-4d05-aff1-0ebe1fb6e9a5"
Path: /sitecore/system/Data Exchange/Data Exchange Tenant for News API/Tenant Settings/RESTful/Applications
DB: master
BranchID: "bc020b09-d391-4dc2-9675-3cf4540fe090"
SharedFields:
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{8D4DDB28-67D0-4960-BB1C-8B6C252C8C9F}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171124T071115Z
